apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: milesplit.mwalden.tech
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: milesplit.mwalden.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: milesplitscraper
          servicePort: 984