name: KubernetesPush

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  test:
    name: Test application before build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "helo!"

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

    - name: Build container image
      run: docker build -t milesplitscraper .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DO }}

    - name: Log in to DigitalOcean Container Registry with
      run: doctl registry login

    - name: Tag image to DigitalOcean Container Registry
      run: docker tag milesplitscraper registry.digitalocean.com/mwalden/milesplitscraper

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/mwalden/milesplitscraper

    - name: Update deployment file
      run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<VERSION>|'${TAG}'|' $GITHUB_WORKSPACE/index.js

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8-mwalden

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/kube

    - name: Verify deployment
      run: kubectl rollout status deployment/milesplitscraper